apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: platform-ref-aws-cnoe
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/platform-ref-aws-cnoe
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This is the reference implementation of [CNOE](https://cnoe.io/) and its toolings on AWS with Crossplane.

    meta.crossplane.io/readme: |
      This is the reference implementation of [CNOE](https://cnoe.io/) and its toolings on AWS with Crossplane.

      To learn more checkout the [GitHub
      repo](https://github.com/upbound/platform-ref-aws-cnoe/) that you can copy and
      customize to meet the exact needs of your organization!
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - configuration: xpkg.upbound.io/upbound/configuration-aws-network
      # renovate: datasource=github-releases depName=upbound/configuration-aws-network
      version: "v0.8.0"
    - configuration: xpkg.upbound.io/upbound/configuration-aws-eks
      # renovate: datasource=github-releases depName=upbound/configuration-aws-eks
      version: "v0.6.0"
    - configuration: xpkg.upbound.io/upbound/configuration-aws-eks-irsa
      # renovate: datasource=github-releases depName=upbound/configuration-aws-eks-irsa
      version: "v0.4.0"
    - configuration: xpkg.upbound.io/upbound/configuration-aws-eks-karpenter
      # renovate: datasource=github-releases depName=upbound/configuration-aws-eks-karpenter
      version: "v0.3.0"
    - configuration: xpkg.upbound.io/upbound/configuration-gitops-argocd
      # renovate: datasource=github-releases depName=upbound/configuration-gitops-argocd
      version: "v0.4.0"
    - configuration: xpkg.upbound.io/upbound/configuration-observability-oss
      # renovate: datasource=github-releases depName=upbound/configuration-observability-oss
      version: "v0.2.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-route53
      # renovate: datasource=github-releases depName=upbound/provider-aws
      version: "v0.47.1"
    - provider: xpkg.upbound.io/upbound/provider-family-aws
      # renovate: datasource=github-releases depName=upbound/provider-aws
      version: "v0.47.1"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-keycloak
      # renovate: datasource=github-releases depName=crossplane-contrib/provider-keycloak
      version: "v0.6.0"
