apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xusers.keycloak.platformref.upbound.io
spec:
  defaultCompositeDeletePolicy: Foreground
  group: keycloak.platformref.upbound.io
  names:
    kind: XUser
    plural: xusers
  claimNames:
    kind: User
    plural: users
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  description: Cluster configuration parameters.
                  properties:
                    id:
                      type: string
                      description: ID of the cnoe installation.
                    username:
                      type: string
                      description: Username
                    firstname:
                      type: string
                      description: FirstName
                    lastname:
                      type: string
                      description: LastName
                    initialPassword:
                      items:
                        properties:
                          temporary:
                            type: boolean
                          valueSecretRef:
                            description: A SecretKeySelector is a reference to a secret
                              key in an arbitrary namespace.
                            properties:
                              key:
                                description: The key to select.
                                type: string
                              name:
                                description: Name of the secret.
                                type: string
                              namespace:
                                description: Namespace of the secret.
                                type: string
                            required:
                              - key
                              - name
                              - namespace
                            type: object
                        required:
                          - valueSecretRef
                        type: object
                      type: array
                    email:
                      type: string
                      description: Email
                    group:
                      type: string
                      description: select group for user
                      enum:
                        - argocd-admin
                        - backstage-admin
                    deletionPolicy:
                      description: Delete the external resources when the Claim/XR is deleted. Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                      type: string
                      default: Delete
                    providerConfigName:
                      description: Crossplane ProviderConfig to use for provisioning this resources
                      type: string
                      default: default
                  required:
                    - deletionPolicy
                    - email
                    - firstname
                    - group
                    - id
                    - lastname
                    - providerConfigName
                    - username
              required:
                - parameters
            status:
              type: object
              properties:
                user:
                  description: Freeform field containing status information for user
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
