name: yamllint
on: [pull_request]
jobs:
  yamllint:
    name: runner / yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - name: yamllint
        uses: reviewdog/action-yamllint@290d92c84b22627946efc7fd6f038ade2d2beede # v1.25.0
        with:
          reporter: github-pr-review
          filter_mode: nofilter
          yamllint_flags: 'apis/'
          fail_on_error: true
